# Created by trellis-cli v1.11.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  catalog.ifloortape.com:
    site_hosts:
    - canonical: catalog.ifloortape.com
      redirects: []
    local_path: ../site
    branch: master
    repo: git@github.com:modernmediagrp/2catalog.ifloortape.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
